language: python
python:
  - "3.6"
sudo: false
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source=app manage.py test app
after_success:
  - coveralls